###############################################################################
# PHP-FPM Upstreams
# Each upstream maps to an isolated PHP-FPM container by container name
###############################################################################

upstream php83 {
    server php83:9000;
    keepalive 16;
}

upstream php82 {
    server php82:9000;
    keepalive 16;
}

upstream php81 {
    server php81:9000;
    keepalive 16;
}

upstream php80 {
    server php80:9000;
    keepalive 16;
}

upstream php74 {
    server php74:9000;
    keepalive 16;
}

upstream php73 {
    server php73:9000;
    keepalive 16;
}

upstream php72 {
    server php72:9000;
    keepalive 16;
}

upstream php71 {
    server php71:9000;
    keepalive 16;
}

upstream php70 {
    server php70:9000;
    keepalive 16;
}

upstream php56 {
    server php56:9000;
    keepalive 16;
}
